
export const translations = {
  en: {
    // Create Event
    'newEvent': 'New Event',
    'eventTitle': 'Event Title',
    'eventDescription': 'Description (optional)',
    'eventDateTime': 'Date & Time',
    'eventMultiplePollCheckbox': 'Multiple Choice',
    'eventMultiplePollCheckboxTooltip': 'Selection of multiple options by users or selection of only one option',
    'eventMultipleBookingCheckbox': 'Multiple Booking',
    'eventMultipleBookingCheckboxTooltip': 'The ability to reserve a time slot by more than one user',
    'addTime': 'Add Time',
    'deleteSlots': 'Delete All',
    'confirmDeleteAllSlots': 'Are you sure you want to delete all selected dates and time slots?',
    'HomePageMainButton': 'Create New Event',
    'CreateEventPageMainButton': 'Create Event',
    'formNotTitleDate': 'To create an event, specify a title and time slots',
    'formNotTitle': 'To create an event, specify a title',
    'formNotDate': 'To create an event, specify time slots (min 2 slots)',
    'eventType': 'Event Type',
    'eventTypePoll': 'Poll',
    'eventTypeBooking': 'Booking',
    'noEventsFound': 'Events not found',
    'otherEvents': 'Participate',
    'myEvents': 'My Events',
    'help-create-event-tooltip': 'Poll — vote for time. Booking — reserve a slot.',
    'eventFinalizade': 'Finalized',
    'participant_count': 'Participants',
    'booked_count': 'Booked',
    'eventDetailHeader': 'Event',
    'pollEventTooltip': 'Poll — vote for time',
    'bookingEventTooltip': 'Booking — reserve a slot',
    'cancelEventButton': 'Cancel Event',
    'editEventButton': 'Edit',
    'createdBy': 'Created by',
    'eventPollMultipleChoiceTrue': '✓ Multiple choices are allowed',
    'eventPollMultipleChoiceFalse': '× Only one option can be selected',
    'eventBookingMultipleChoiceTrue': '✓ Multiple booking are allowed',
    'eventBookingMultipleChoiceFalse': '× Only one user per slot',
    'eventDateTimeInfo': 'Available Times',
    'confirmChoiceSlots': 'Confirm Choice',
    'confirmDeleteEvent': 'Are you sure you want to delete this event?',
    "eventDeletedSuccessfully": "Event successfully deleted",
    "errorDeletingEvent": "Error when deleting an event",
    'editEvent': 'Edit Event',
    'editPageSaveChanges': 'Save',
    'editPageCancel': 'Cancel',
    'votes': 'Votes',
    'booked': 'Booked',
    'noEvents': 'No events',
    "confirmDeleteBookedSlot": "This slot is already booked. Are you sure you want to delete it?",
    "confirmDeleteBookedDate": 'This date has booked. Are you sure you want to delete it?',
    'confirmDeleteVotedDate': 'This date has votes. Are you sure you want to delete it?',
    "confirmDeleteVotedSlot": "This slot has already been voted on. Are you sure you want to delete it?",
    'timezoneInfoLocal': 'The time is indicated in your time zone',
    'timezoneInfoEvent': 'The time is indicated in time zone of event',
    'titleParticipants': 'Participants',
    'errorConfirmingSelection': 'Error saving selection',
    'selectionConfirmedSuccessfully': 'Your selection has been successfully saved!',
    'errorSubmittingVotes': 'Error sending votes',
    'editSelectionButton': 'Edit Choice',
    "selectSlotToFinalize": "Select a slot to complete poll",
    'finalizePollButton': 'Finaliezed Poll',
    'unfinalizePollButton': 'Reopen Poll',
    'eventFinalizedSuccessfully': 'Poll completed',
    'errorFinalizedEvent': 'Error finalized poll',
    'unfinalizePoll': 'Are you sure you want to reopen the poll?',
    'eventUnfinalizeSuccessfully': 'The poll has been successfully reopen.',
    'errorUnfinalizeEvent': 'Poll reopening error',
    "localTime": "My Time",
    "eventTime": "Event Time",
    "switchToLocalTime": "Switch to local time",
    "switchToEventTime": "Switch to event time",
    'templateButton': 'Template',

    'eventLocation': 'Location',
    'eventLocationPlaceholder': 'Address, Zoom/Meet link, or other location',
    'addLocationOnFinalize': 'Add meeting location',
    'locationAdded': 'Location added',
    'addToCalendarButton': 'Add to Calendar',
  },
  ru: {
    // Create Event
    'newEvent': 'Новое событие',
    'eventTitle': 'Название события',
    'eventDescription': 'Описание (необязательно)',
    'eventDateTime': 'Выбор даты и времени',
    'eventMultiplePollCheckbox': 'Множественный выбор',
    'eventMultiplePollCheckboxTooltip': 'Выбор нескольких вариантов пользователями или выбор только одного',
    'eventMultipleBookingCheckbox': 'Множественная бронь',
    'eventMultipleBookingCheckboxTooltip': 'Возможность бронировать слот времени более чем одним пользователем',
    'addTime': 'Добавить время',
    'deleteSlots': 'Сбросить',
    'confirmDeleteAllSlots': 'Вы уверены, что хотите удалить все выбранные даты и временные слоты?',
    'HomePageMainButton': 'Создать событие',
    'CreateEventPageMainButton': 'Создать',
    'formNotTitleDate': 'Для создания события укажите название и доступное время',
    'formNotTitle': 'Для создания события укажите название',
    'formNotDate': 'Для создания события выберите доступное время (не меньше 2 вариантов)',
    'eventType': 'Тип события',
    'eventTypePoll': 'Опрос',
    'eventTypeBooking': 'Бронь',
    'noEventsFound': 'Нет доступных событий',
    'otherEvents': 'Участвую',
    'myEvents': 'Мои события',
    'help-create-event-tooltip': 'Опрос — голосование за время. Бронь — занять слот.',
    'eventFinalizade': 'Завершено',
    'participant_count': 'Участников',
    'booked_count': 'Забронировано',
    'eventDetailHeader': 'Событие',
    'pollEventTooltip': 'Опрос — голосование за время',
    'bookingEventTooltip': 'Бронь — занять слот',
    'cancelEventButton': 'Удалить',
    'editEventButton': 'Изменить',
    'createdBy': 'Создан',
    'eventPollMultipleChoiceTrue': '✓ Множественный выбор разрешён',
    'eventPollMultipleChoiceFalse': '× Можно выбрать только один вариант',
    'eventBookingMultipleChoiceTrue': '✓ Множественная бронь разрешена',
    'eventBookingMultipleChoiceFalse': '× Только один пользователь на один слот',
    'eventDateTimeInfo': 'Доступное время',
    'confirmChoiceSlots': 'Подтвердить выбор',
    'confirmDeleteEvent': 'Вы уверены, что хотите удалить это событие?',
    "eventDeletedSuccessfully": "Событие успешно удалено",
    "errorDeletingEvent": "Ошибка при удалении события",
    'editPageSaveChanges': 'Сохранить',
    'editPageCancel': 'Отменить',
    'editEvent': 'Редактирование события',
    'votes': 'Голосов',
    'booked': 'Забронировано',
    'noEvents': 'Нет доступных событий',
    "confirmDeleteBookedSlot": "Этот слот уже забронирован. Вы уверены, что хотите его удалить?",
    "confirmDeleteBookedDate": 'У этой даты есть брони. Вы уверены, что хотите ее удалить?',
    'confirmDeleteVotedDate': 'У этой даты есть голоса. Вы уверены, что хотите ее удалить?',
    "confirmDeleteVotedSlot": "За этот слот уже проголосовали. Вы уверены, что хотите его удалить?",
    'timezoneInfoLocal': 'Время указано в вашем часовом поясе',
    'timezoneInfoEvent': 'Время указано в часовом поясе события',
    'titleParticipants': 'Участники',
    'errorConfirmingSelection': 'Ошибка при сохранении выбора',
    'selectionConfirmedSuccessfully': 'Ваш выбор успешно сохранён!',
    'errorSubmittingVotes': 'Ошибка при отправке голосов',
    'editSelectionButton': 'Изменить выбор',
    "selectSlotToFinalize": "Выберите слот для завершения опроса",
    'finalizePollButton': 'Завершить опрос',
    'unfinalizePollButton': 'Возобновить',
    'eventFinalizedSuccessfully': 'Опрос завершен',
    'errorFinalizedEvent': 'Ошибка завершения опроса',
    'unfinalizePoll': 'Вы уверены что хотите возобновить опрос?',
    'eventUnfinalizeSuccessfully': 'Опрос успешно возобновлен',
    'errorUnfinalizeEvent': 'Ошибка возобновления опроса',
    "localTime": "Моё время",
    "eventTime": "Время события",
    "switchToLocalTime": "Переключить на мое время",
    "switchToEventTime": "Переключить на время события",
    'templateButton': 'Шаблон',

    'eventLocation': 'Место встречи',
    'eventLocationPlaceholder': 'Адрес, ссылка на Zoom/Meet или другая локация',
    'addLocationOnFinalize': 'Добавить место встречи',
    'locationAdded': 'Место встречи добавлено',
    'addToCalendarButton': 'Добавить в календарь',
  }
};
